//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Part1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecycleBin
    {
        public int Id { get; set; }
        public string InputS { get; set; }
        public int InputN { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public int BinID { get; set; }
    }
}
